### PR TITLE
Added tempUnit param

### PR DESCRIPTION
**Pull request by detheridge02**
[Example](https://de-weather-overlay.surge.sh/?lat=39.704555&lon=-105.087551&tempUnit=metric)
Added 'tempUnit' param which takes either 'imperial' or 'metric' as values. 
The displayed temperature value and symbol are set accordingly. 
If neither is provided, or the value is invalid, the unit is set to imperial.

Alt text also added to the weather symbol but this needs improving as this is currently set to symbol_code.

The UK localisation commit can be ignored as this was replaced by the tempURL parameter.

### CODE REVIEW

**Review by drillskibo — CHANGES_REQUESTED** [review]
* Please remove your package-lock.json from the commits
* `surge`  is not a required dependency, I would not include it in the package.json
* I would not create a CNAME file and ignore it as well.
These are not steps you need to commit, but things you did during your own development.
Other than that, it looks like a nice upgrade ! 😄

**Comment by detheridge02** [comment]
Thanks @drillskibo . Updates committed

**Comment by drillskibo** [comment]
> Thanks @drillskibo . Updates committed

https://github.com/CodingGarden/weather-overlay/pull/3#pullrequestreview-1176473530
Follow this please :)

**Comment by detheridge02** [comment]
> Follow this please :)

package-lock.json returned to upstream version and removed from .gitignore :) 
Cheers

**Comment by detheridge02** [comment]
Closing to tidy up my fork and will resubmit later

**Pull request closed without merging**
